# FROM node:16-alpine3.15 AS builder
FROM node:16-slim AS builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm i

COPY . .
RUN npm run build

FROM nginx:1.23.0
WORKDIR /app
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder ./app/build ./

# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
