FROM node:16-slim AS build

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm i

COPY . .
RUN npm run build

FROM nginx:1.23.0
WORKDIR /app
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build ./app/build ./
