FROM node:18-alpine3.15 AS build

ENV NODE_VERSION 16.13.0

WORKDIR /build
COPY package.json package-lock.json ./
RUN npm i

COPY . .
RUN npm run build

FROM nginx:1.23.0
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /build/build /frontend/build
