version: "3.9"
services:
  web:
    image: rtk.web
    container_name: Web
    build:
      context: .
      dockerfile: Dockerfile-deploy
    ports:
      - 3002:80
    depends_on:
      - json-server

  json-server:
    image: rtk.db
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.json-server
    ports:
      - 3501:3501
   

